name: Fetch News

on:
  schedule:
    - cron: "*/30 * * * *"   # a cada 30 minutos
  workflow_dispatch: {}       # permite correr à mão

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Fetch news
        run: npm run news:fetch

      - name: Commit & push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "news-bot"
            git config user.email "bot@users.noreply.github.com"
            git add -A
            git commit -m "chore(news): ingest RSS"
            git push
          else
            echo "Sem novidades."
          fi
